### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by CakeBaker1** [MegaManSec/SSH-Snake#14]
bash ./Snake.nocomments.sh
bash: line 449: conditional binary operator expected
bash: line 449: syntax error near `'current_ips["$ignored_host"]''
bash: line 449: `[[ -v 'current_ips["$ignored_host"]' || ${#current_ips["$ignored_host"]} -gt 0 ]] && fin'

**Comment by MegaManSec** [comment]
What version of bash are you using? 

Have you made any modifications to the script at all?

**Comment by MegaManSec** [comment]
The script only supports bash4 sorry
