### ISSUE TITLE
Find Symlinked Keys

### ISSUE THREAD

**Issue by dharrigan** [MegaManSec/SSH-Snake#2]
Hi,

In my .ssh directory, I have several private keys that are symlinked (from their actual physical location on my filesystem). The script doesn't follow symlinks (in discovering private keys), thus misses out on other keys to use. Adding a `-L` to the find will find all symlinked keys [around about here](https://github.com/MegaManSec/SSH-Snake/blob/617eb1e3d5de3a03f2a883e1a3f74db8404d073f/Snake.sh#L1016C17-L1016C189).

I would be happy to do a PR for you if you wish.

-=david=-

**Comment by MegaManSec** [comment]
Thanks for the report! I've added the `-L` flag to all of the calls of `find(1)`.

I was initially worried that using `-L` wouldn't be enough, because Snake's `is_file()` may fail, but it should be fine:

```bash
$ echo 1 > file
$ ln -s file sym
$ test -f sym && test -r sym && test -s sym && echo yes
yes
```

The same goes for `is_dir()` -- but it seems fine.

Fixed.
